services:
  rhasspy-satellite:
    image: rhasspy/rhasspy:2.5.11
    container_name: rhasspy-satellite
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./profiles:/profiles
      - /etc/asound.conf:/etc/asound.conf:ro
    command: >
      --user-profiles /profiles
      --profile sv
    privileged: true
