version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  rhasspy:
    image: rhasspy/rhasspy:2.5.11
    container_name: rhasspy-base
    restart: unless-stopped
    ports:
      - "12101:12101"
    volumes:
      - ./profiles:/profiles
    command: >
      --user-profiles /profiles
      --profile sv
    depends_on:
      - mosquitto
